services:
  - type: web
    name: petrol-pump
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y tesseract-ocr
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT