# Generated by Django 5.2.3 on 2026-04-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Vehicle registration number (uppercase letters and digits)', max_length=50, unique=True)),
                ('last_fuel_date', models.DateTimeField(blank=True, help_text='Date/time of last successful fueling', null=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo of the vehicle number plate', upload_to='fuel_logs/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when this log was created')),
                ('vehicle', models.ForeignKey(help_text='Vehicle that received fuel', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='app.vehicle')),
            ],
            options={
                'verbose_name': 'Fuel Log',
                'verbose_name_plural': 'Fuel Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
